/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module ApiEntities {
    /** Generated from AbcSample.Api.Models.CountryResponse **/
    export interface CountryResponse {
        Id: string;
        Description: string;
    }
}
